# Pytorch Basics

In [17]:
import torch as tr

In [2]:
tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

In [3]:
tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

In [5]:
tensor[0]

tensor([[1., 2.],
        [3., 4.]])

**Tensor properties and attributes in pytorch**

In [6]:
tensor.shape

torch.Size([3, 2, 2])

In [7]:
tensor[0].shape

torch.Size([2, 2])

In [8]:
tensor.ndim

3

In [10]:
tensor[1]

tensor([[5., 6.],
        [7., 8.]])

In [9]:
tensor[1,1,0]

tensor(7.)

In [11]:
tensor[1,1,0].item()  # For Getting Scaler Value From Tensor

7.0

In [16]:
tensor[:3, 1, 0]

tensor([3., 7., 1.])

**Creating tensors**

In [20]:
tr.ones((3,3,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [21]:
tr.zeros((1,3,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [28]:
tr.randn_like(tensor)

tensor([[[ 0.8759,  0.0214],
         [-0.7031, -0.2337]],

        [[-0.1598, -0.5308],
         [-0.0683, -0.3840]],

        [[-0.3258,  0.2680],
         [ 1.3206, -0.3106]]])

In [29]:
tr.randn((3,3))

tensor([[ 0.0944, -1.2917, -1.2558],
        [ 0.3162,  0.8001,  0.1941],
        [ 0.9318, -0.8121,  1.7354]])

**Basic operation on tensor**

In [30]:
tensor-5

tensor([[[-4., -3.],
         [-2., -1.]],

        [[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4., -5.],
         [-4., -3.]]])

In [31]:
tensor*10

tensor([[[10., 20.],
         [30., 40.]],

        [[50., 60.],
         [70., 80.]],

        [[90.,  0.],
         [10., 20.]]])

In [32]:
tensor/2

tensor([[[0.5000, 1.0000],
         [1.5000, 2.0000]],

        [[2.5000, 3.0000],
         [3.5000, 4.0000]],

        [[4.5000, 0.0000],
         [0.5000, 1.0000]]])

In [33]:
tensor.mean() # Mean of tensor

tensor(4.)

In [34]:
tensor.std() # Standard deviation

tensor(2.9848)

In [35]:
 """It means that the mean is taken along 
   the first dimension (dimension index starts at 0) of the tensor"""
tensor.mean(0)

tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])

# Importing Neural Network With Pytorch

In [36]:
import torch.nn as nn

**Creating a linear layer**

In [37]:
linear = nn.Linear(10, 2)
example_input = torch.randn(3, 10)
example_output = linear(example_input)
example_output

tensor([[-0.0268,  1.1823],
        [-0.1940,  0.0876],
        [ 1.0420,  0.8522]], grad_fn=<AddmmBackward0>)

**Creating an object as activation function (ReLU)**

In [38]:
relu = nn.ReLU()
relu_output = relu(example_output)
relu_output

tensor([[0.0000, 1.1823],
        [0.0000, 0.0876],
        [1.0420, 0.8522]], grad_fn=<ReluBackward0>)

**Creating a object for batch normalization**

In [39]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output = batchnorm(relu_output)
batchnorm_output

tensor([[-0.7071,  1.0359],
        [-0.7071, -1.3517],
        [ 1.4142,  0.3158]], grad_fn=<NativeBatchNormBackward0>)

**Creating a sequential model**

In [40]:
mlp_layer = nn.Sequential(
    nn.Linear(5, 2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

test_example = torch.randn(5,5) + 1
print("input: ")
print(test_example)
print("output: ")
print(mlp_layer(test_example))

input: 
tensor([[ 1.0968, -0.2090,  0.3104,  1.2423,  0.2565],
        [ 1.8925,  1.9223,  1.6289, -0.8615,  1.9835],
        [ 3.1551,  2.5479,  1.1332,  0.2151,  1.5137],
        [ 2.2989, -0.1599,  0.4860,  1.1429,  0.9725],
        [ 0.6227,  0.5559,  1.1680, -0.2269,  0.4080]])
output: 
tensor([[1.0357, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 1.7477],
        [0.3563, 0.1044],
        [0.8197, 0.0000]], grad_fn=<ReluBackward0>)


# Optimization

In [41]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(), lr=1e-1)

In [42]:
train_example = torch.randn(100,5) + 1
adam_opt.zero_grad()

# We'll use a simple loss function of mean distance from 1
# torch.abs takes the absolute value of a tensor
cur_loss = torch.abs(1 - mlp_layer(train_example)).mean()

cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7834, grad_fn=<MeanBackward0>)


In [43]:
class ExampleModule(nn.Module):
    def __init__(self, input_dims, output_dims):
        super(ExampleModule, self).__init__()
        self.linear = nn.Linear(input_dims, output_dims)
        self.exponent = nn.Parameter(torch.tensor(1.))

    def forward(self, x):
        x = self.linear(x)

        # This is the notation for element-wise exponentiation, 
        # which matches python in general
        x = x ** self.exponent 
        
        return x

In [44]:
example_model = ExampleModule(10, 2)
list(example_model.parameters())

[Parameter containing:
 tensor(1., requires_grad=True),
 Parameter containing:
 tensor([[-0.0747,  0.0720, -0.1888,  0.1665, -0.2265,  0.2188, -0.1030,  0.2436,
           0.0692, -0.1669],
         [-0.3081,  0.1533, -0.0430,  0.2525,  0.2850,  0.3080, -0.1822, -0.0738,
           0.1754, -0.0195]], requires_grad=True),
 Parameter containing:
 tensor([0.1506, 0.2391], requires_grad=True)]

In [45]:
list(example_model.named_parameters())

[('exponent',
  Parameter containing:
  tensor(1., requires_grad=True)),
 ('linear.weight',
  Parameter containing:
  tensor([[-0.0747,  0.0720, -0.1888,  0.1665, -0.2265,  0.2188, -0.1030,  0.2436,
            0.0692, -0.1669],
          [-0.3081,  0.1533, -0.0430,  0.2525,  0.2850,  0.3080, -0.1822, -0.0738,
            0.1754, -0.0195]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([0.1506, 0.2391], requires_grad=True))]

In [46]:
input = torch.randn(2, 10)
example_model(input)

tensor([[0.1640, 0.6303],
        [0.2011, 0.6314]], grad_fn=<PowBackward1>)